server:
  port : 8089
  servlet:
    contextPath: /union-service
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://userAdmin:passwordAdmin@localhost:27017/union?authSource=admin
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 5MB
mongodb:
  database: ${MONGODB_NAME:union}


#just temp variables needed to satisfy configuration resolver bean
#unitl we find some kind of workaround
keycloak:
  enabled: true
  auth-server-url: ${KEYCLOAK_URL_WITH_PATH:mock}
  realm: ${CLIENT_RELM_NAME:mock}
  resource: ${KEYCLOAK_CLIENT_NAME:mock}
  public-client: true
  bearer-only: true

services:
  profile-service:
    url: ${PROFILE_SERVICE_URL:http://localhost:8082/profile-service}
  forum-service:
    url: ${FORUM_SERVICE_URL:http://localhost:8085}
  calendar-service:
    url: ${CALENDAR_SERVICE_URL:http://localhost:8080/calendar-service}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

# root folder where all uploaded file will go
upload:
  directory:
    rootpath: /user/home/wevolv/