server:
  error:
    include-message: always
  port: 8080
  servlet:
    contextPath: /payment-service
spring:
  application:
    name: payment-api
  data:
    mongodb:
     uri: ${MONGODB_URI}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mongodb:
  database: ${MONGODB_NAME}

services:
  profile-service:
    url: ${PROFILE_SERVICE_URL}
    auto-index-creation: true

#just temp variables needed to satisfy configuration resolver bean
#unitl we find some kind of workaround
keycloak:
  enabled: true
  auth-server-url: ${KEYCLOAK_URL_WITH_PATH:mock}
  realm: ${CLIENT_RELM_NAME:mock}
  resource: ${KEYCLOAK_CLIENT_NAME:mock}
  public-client: true
  bearer-only: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

stripe:
  public-key: ${STRIPE_PUBLIC_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
