server:
  error:
    include-message: always
  port: 8086
  servlet:
    contextPath: /user-service
spring:
  application:
    name: user-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
mongodb:
  database: ${MONGODB_NAME}

##==================Keycloak properties================#
#keycloak:
#  realm: registerapirealm
#  auth-server-url: http://localhost:8080/auth
#  ssl-required: external
#  #keycloak resource is the client ID
#  resource: registerApiClient
#  credentials:
#    secret: 12a658ea-b728-4f53-9948-492ef470363f
#  #The line below will prevent redirect to login page
#  bearer-only: true
#
##Admin credentials, reading system env variables
#admin:
#  username: buzov.tea@gmail.com
#  password: teatea35
##

#==================Keycloak properties================#
keycloak:
  realm: ${CLIENT_RELM_NAME}
  auth-server-url: ${KEYCLOAK_URL_WITH_PATH}
  ssl-required: external
  #keycloak resource is the client ID
  resource: ${KEYCLOAK_CLIENT_NAME}
  #replace secret with your key
  #The line below will prevent redirect to login page
  bearer-only: true

#Admin credentials, reading system env variables
admin:
  username: ${KEYCLOAK_ADMIN_USER}
  password: ${KEYCLOAK_ADMIN_PASSWORD}

invite:
  base-url: ${REGISTRATION_SERVICE_URL}
  qr-code-height: 300
  qr-code-width: 300


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

