server:
  error:
    include-message: always
  port: 8080
  servlet:
    contextPath: /notification-service
spring:
  application:
    name: push-notification-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}
      #uri: mongodb://tea:teapassword@localhost:27017/user?authSource=admin
mongodb:
  database: ${MONGODB_NAME}

app:
  firebase-configuration-file: wevolv-push-notification-firebase-adminsdk-34kta-745079e21f.json

